name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: | 
          cdk/yarn.lock
          front/yarn.lock
    - name: Yarn install
      working-directory: front
      run: |
        yarn install --frozen-lockfile
    - name: Build
      working-directory: front
      run: |
        yarn build
    - name: Yarn Deploy
      working-directory: cdk
      run: | 
        yarn install --frozen-lockfile
    - name: Cdk Deploy
      working-directory: cdk
      run: | 
        yarn cdk:deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Deploy to S3
      #-- GitHub上に登録した変数を持ってくる --#
      #-- 仮想マシン上でコマンドを実行 --#
      run:
        aws s3 sync --delete --region ap-northeast-1 ./front/.next/ s3://FirstEdgeBucket/.next
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


